Python 3 does not support unicode type
Attempting to provide python 3 compatibility with six.
```
NameError: global name 'unicode' is not defined
```