Fix options import as instead.
Python 2.7 and 2.6 fail horribly due to this modification.
importing as to avoid naming issues.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 96, in run
    self.client._sync_flush()
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 484, in _sync_flush
    url = options.host + options.endpoints['batch']
NameError: global name 'options' is not defined
```