Python 3 does not support unicode(...)
```
NameError: global name 'unicode' is not defined
```
https://travis-ci.org/duly/analytics-python/jobs/21861913#L1198
http://pythonhosted.org//six/#six.u