Fix ImportError: No module named stats
11 Tests Fail due to the issues on Lines 11-13.
>EXAMPLE<
```
Traceback (most recent call last):
  File "test.py", line 37, in setUp
    analytics.init(secret, log_level=logging.DEBUG)
  File "/home/travis/build/duly/analytics-python/analytics/__init__.py", line 33, in init
    from analytics.client import Client
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 11, in <module>
    from stats import Statistics
ImportError: No module named stats
```